-- Central invoice/CFDI registry. UUID uniqueness is enforced inside the same
-- transaction that saves or finalizes a CLC document.

create table if not exists public.clc_invoice_registry (
  id bigint generated by default as identity primary key,
  uuid text not null,
  serie text,
  folio text,
  rfc_emisor text not null,
  nombre_emisor text,
  rfc_receptor text,
  fecha_factura date,
  subtotal numeric(14,2) not null default 0,
  descuento numeric(14,2) not null default 0,
  iva numeric(14,2) not null default 0,
  isr numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  concepto text,
  xml_hash text,
  clc_id text not null,
  partida_id text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_reason text,
  constraint clc_invoice_registry_status_check
    check (status in ('active', 'removed', 'cancelled', 'replaced')),
  constraint clc_invoice_registry_uuid_normalized_check
    check (uuid = lower(trim(uuid)))
);

create unique index if not exists clc_invoice_registry_active_uuid_uidx
on public.clc_invoice_registry (uuid)
where status = 'active';

create index if not exists clc_invoice_registry_clc_idx
on public.clc_invoice_registry (clc_id, status);

create index if not exists clc_invoice_registry_xml_hash_idx
on public.clc_invoice_registry (xml_hash)
where xml_hash is not null and xml_hash <> '';

alter table public.clc_invoice_registry enable row level security;
revoke all on table public.clc_invoice_registry from anon, authenticated;

drop trigger if exists clc_invoice_registry_updated_at on public.clc_invoice_registry;
create trigger clc_invoice_registry_updated_at
before update on public.clc_invoice_registry
for each row execute function public.clc_set_updated_at();

create or replace function public.clc_normalize_invoice_uuid(p_uuid text)
returns text
language sql
immutable
as $$
  select lower(trim(coalesce(p_uuid, '')));
$$;

create or replace function public.clc_normalize_rfc(p_rfc text)
returns text
language sql
immutable
as $$
  select upper(regexp_replace(trim(coalesce(p_rfc, '')), '\s+', '', 'g'));
$$;

create or replace function public.clc_invoice_numeric(p_item jsonb, p_field text)
returns numeric
language sql
immutable
as $$
  select case
    when nullif(trim(p_item ->> p_field), '') ~ '^-?\d+(\.\d+)?$'
      then (p_item ->> p_field)::numeric
    else 0
  end;
$$;

create or replace function public.clc_validate_provider_bank_catalogs(p_catalogs jsonb)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_invalid_provider_id text;
  v_duplicate_default_provider_id text;
begin
  select bank.value ->> 'providerId'
  into v_invalid_provider_id
  from jsonb_array_elements(
    case when jsonb_typeof(p_catalogs -> 'bancos') = 'array' then p_catalogs -> 'bancos' else '[]'::jsonb end
  ) bank(value)
  where nullif(trim(bank.value ->> 'providerId'), '') is not null
    and not exists (
      select 1
      from jsonb_array_elements(
        case when jsonb_typeof(p_catalogs -> 'proveedores') = 'array' then p_catalogs -> 'proveedores' else '[]'::jsonb end
      ) provider(value)
      where provider.value ->> 'id' = bank.value ->> 'providerId'
    )
  limit 1;

  if v_invalid_provider_id is not null then
    raise exception 'La cuenta bancaria referencia un proveedor inexistente: %.', v_invalid_provider_id
      using errcode = '23503';
  end if;

  select bank.value ->> 'providerId'
  into v_duplicate_default_provider_id
  from jsonb_array_elements(
    case when jsonb_typeof(p_catalogs -> 'bancos') = 'array' then p_catalogs -> 'bancos' else '[]'::jsonb end
  ) bank(value)
  where nullif(trim(bank.value ->> 'providerId'), '') is not null
    and coalesce(bank.value ->> 'active', 'true') <> 'false'
    and coalesce(bank.value ->> 'isDefault', 'false') = 'true'
  group by bank.value ->> 'providerId'
  having count(*) > 1
  limit 1;

  if v_duplicate_default_provider_id is not null then
    raise exception 'Un proveedor no puede tener más de una cuenta bancaria default.'
      using errcode = '23505';
  end if;
end;
$$;

create or replace function public.clc_validate_provider_bank_relation(p_document jsonb)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_catalogs jsonb;
  v_provider_id text;
  v_bank_provider_id text;
begin
  select catalogs into v_catalogs
  from public.clc_app_settings
  where id = 'default';

  if coalesce(jsonb_typeof(v_catalogs), 'null') <> 'object' then
    return;
  end if;

  select provider.value ->> 'id'
  into v_provider_id
  from jsonb_array_elements(
    case when jsonb_typeof(v_catalogs -> 'proveedores') = 'array' then v_catalogs -> 'proveedores' else '[]'::jsonb end
  ) provider(value)
  where coalesce(provider.value ->> 'active', 'true') <> 'false'
    and public.clc_normalize_rfc(provider.value ->> 'rfc') = public.clc_normalize_rfc(p_document ->> 'proveedorRfc')
  limit 1;

  select nullif(trim(bank.value ->> 'providerId'), '')
  into v_bank_provider_id
  from jsonb_array_elements(
    case when jsonb_typeof(v_catalogs -> 'bancos') = 'array' then v_catalogs -> 'bancos' else '[]'::jsonb end
  ) bank(value)
  where coalesce(bank.value ->> 'active', 'true') <> 'false'
    and (
      (
        nullif(regexp_replace(coalesce(bank.value ->> 'clabe', ''), '\s+', '', 'g'), '') is not null
        and regexp_replace(coalesce(bank.value ->> 'clabe', ''), '\s+', '', 'g')
          = regexp_replace(coalesce(p_document ->> 'bancoClabe', ''), '\s+', '', 'g')
      )
      or (
        regexp_replace(coalesce(bank.value ->> 'cuenta', ''), '\s+', '', 'g')
          = regexp_replace(coalesce(p_document ->> 'bancoCuenta', ''), '\s+', '', 'g')
        and upper(trim(coalesce(bank.value ->> 'nombre', '')))
          = upper(trim(coalesce(p_document ->> 'bancoNombre', '')))
      )
    )
  limit 1;

  if not found then
    -- Manual capture remains compatible until the new account is added to catalogs.
    return;
  end if;

  if v_bank_provider_id is null then
    raise exception 'La cuenta bancaria seleccionada no está vinculada a ningún proveedor.'
      using errcode = '23514';
  end if;

  if v_provider_id is null or v_provider_id <> v_bank_provider_id then
    raise exception 'La cuenta bancaria seleccionada no pertenece al proveedor seleccionado.'
      using errcode = '23514';
  end if;
end;
$$;

create or replace function public.clc_save_catalogs(
  p_catalogs jsonb,
  p_app_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.clc_require_app_key(p_app_key);
  perform public.clc_validate_catalogs(p_catalogs);
  perform public.clc_validate_provider_bank_catalogs(p_catalogs);

  update public.clc_app_settings
  set catalogs = p_catalogs
  where id = 'default';

  return public.clc_build_app_meta();
end;
$$;

-- Link legacy accounts only when existing CLC documents identify exactly one
-- provider RFC for that account. Ambiguous or unused accounts remain unlinked
-- so an administrator can assign them explicitly in Catalogos.
with current_settings as (
  select catalogs
  from public.clc_app_settings
  where id = 'default'
),
bank_rows as (
  select bank.value, bank.ordinality
  from current_settings
  cross join lateral jsonb_array_elements(
    case when jsonb_typeof(catalogs -> 'bancos') = 'array' then catalogs -> 'bancos' else '[]'::jsonb end
  ) with ordinality bank(value, ordinality)
),
bank_usage as (
  select
    bank.ordinality,
    case
      when count(distinct public.clc_normalize_rfc(document.payload ->> 'proveedorRfc')) = 1
        then min(public.clc_normalize_rfc(document.payload ->> 'proveedorRfc'))
      else null
    end as provider_rfc
  from bank_rows bank
  left join public.clc_documents document
    on regexp_replace(coalesce(bank.value ->> 'cuenta', ''), '\s+', '', 'g')
      = regexp_replace(coalesce(document.payload ->> 'bancoCuenta', ''), '\s+', '', 'g')
   and regexp_replace(coalesce(bank.value ->> 'clabe', ''), '\s+', '', 'g')
      = regexp_replace(coalesce(document.payload ->> 'bancoClabe', ''), '\s+', '', 'g')
  group by bank.ordinality
),
inferred as (
  select
    bank.value,
    bank.ordinality,
    provider.value ->> 'id' as provider_id
  from bank_rows bank
  join bank_usage usage on usage.ordinality = bank.ordinality
  left join current_settings on true
  left join lateral jsonb_array_elements(
    case when jsonb_typeof(catalogs -> 'proveedores') = 'array' then catalogs -> 'proveedores' else '[]'::jsonb end
  ) provider(value)
    on public.clc_normalize_rfc(provider.value ->> 'rfc') = usage.provider_rfc
),
ranked as (
  select
    inferred.*,
    row_number() over (partition by provider_id order by ordinality) as provider_account_number
  from inferred
),
rebuilt as (
  select jsonb_agg(
    case
      when nullif(trim(value ->> 'providerId'), '') is null and provider_id is not null then
        jsonb_set(
          jsonb_set(value, '{providerId}', to_jsonb(provider_id), true),
          '{isDefault}',
          to_jsonb(
            provider_account_number = 1
            and not exists (
              select 1
              from bank_rows existing
              where existing.value ->> 'providerId' = ranked.provider_id
                and coalesce(existing.value ->> 'isDefault', 'false') = 'true'
            )
          ),
          true
        )
      else value
    end
    order by ordinality
  ) as bancos
  from ranked
)
update public.clc_app_settings settings
set catalogs = jsonb_set(settings.catalogs, '{bancos}', rebuilt.bancos, true)
from rebuilt
where settings.id = 'default'
  and rebuilt.bancos is not null;

create or replace function public.clc_check_invoice_uuid(
  p_uuid text,
  p_current_clc_id text default null,
  p_current_partida_id text default null,
  p_app_key text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_usage jsonb;
begin
  perform public.clc_require_app_key(p_app_key);

  select jsonb_build_object(
    'uuid', registry.uuid,
    'clcId', registry.clc_id,
    'folio', coalesce(nullif(document.folio, ''), 'BORRADOR'),
    'partidaId', coalesce(registry.partida_id, '')
  )
  into v_usage
  from public.clc_invoice_registry registry
  left join public.clc_documents document on document.id = registry.clc_id
  where registry.uuid = public.clc_normalize_invoice_uuid(p_uuid)
    and registry.status = 'active'
    and not (
      registry.clc_id = coalesce(p_current_clc_id, '')
      and coalesce(registry.partida_id, '') = coalesce(p_current_partida_id, '')
    )
  limit 1;

  return v_usage;
end;
$$;

create or replace function public.clc_sync_invoice_registry(p_document jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clc_id text := nullif(trim(p_document ->> 'id'), '');
  v_provider_rfc text := public.clc_normalize_rfc(p_document ->> 'proveedorRfc');
  v_provider_name text := nullif(trim(p_document ->> 'proveedorNombre'), '');
  v_items jsonb := case
    when jsonb_typeof(p_document -> 'items') = 'array' then p_document -> 'items'
    else '[]'::jsonb
  end;
  v_item jsonb;
  v_uuid text;
  v_item_id text;
  v_cfdi jsonb;
  v_registry_id bigint;
  v_duplicate_uuid text;
  v_conflict_folio text;
  v_conflict_uuid text;
  v_conflict_hash text;
begin
  select public.clc_normalize_invoice_uuid(item.value ->> 'numFactura')
  into v_duplicate_uuid
  from jsonb_array_elements(v_items) item(value)
  where public.clc_normalize_invoice_uuid(item.value ->> 'numFactura') <> ''
  group by public.clc_normalize_invoice_uuid(item.value ->> 'numFactura')
  having count(*) > 1
  limit 1;

  if v_duplicate_uuid is not null then
    raise exception 'El UUID % está duplicado dentro de esta CLC.', upper(v_duplicate_uuid)
      using errcode = '23505';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(invoice.uuid, 20260610))
  from (
    select distinct public.clc_normalize_invoice_uuid(item.value ->> 'numFactura') as uuid
    from jsonb_array_elements(v_items) item(value)
    where public.clc_normalize_invoice_uuid(item.value ->> 'numFactura') <> ''
    order by uuid
  ) invoice;

  select nullif(trim(item.value -> 'cfdi' ->> 'xmlHash'), '')
  into v_conflict_hash
  from jsonb_array_elements(v_items) item(value)
  where nullif(trim(item.value -> 'cfdi' ->> 'xmlHash'), '') is not null
  group by nullif(trim(item.value -> 'cfdi' ->> 'xmlHash'), '')
  having count(*) > 1
  limit 1;

  if v_conflict_hash is not null then
    raise exception 'El mismo archivo XML está duplicado dentro de esta CLC.'
      using errcode = '23505';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(v_items) item(value)
    where public.clc_normalize_rfc(item.value -> 'cfdi' ->> 'rfcEmisor') <> ''
      and public.clc_normalize_rfc(item.value -> 'cfdi' ->> 'rfcEmisor') <> v_provider_rfc
  ) then
    raise exception 'El RFC emisor del XML no coincide con el RFC del proveedor seleccionado.'
      using errcode = '23514';
  end if;

  select registry.uuid, coalesce(nullif(document.folio, ''), 'BORRADOR')
  into v_conflict_uuid, v_conflict_folio
  from public.clc_invoice_registry registry
  left join public.clc_documents document on document.id = registry.clc_id
  join jsonb_array_elements(v_items) item(value)
    on registry.uuid = public.clc_normalize_invoice_uuid(item.value ->> 'numFactura')
  where registry.status = 'active'
    and not (
      registry.clc_id = v_clc_id
      and coalesce(registry.partida_id, '') = coalesce(item.value ->> 'id', '')
    )
  limit 1;

  if v_conflict_uuid is not null then
    raise exception 'Esta factura ya está registrada en la CLC %.', v_conflict_folio
      using errcode = '23505';
  end if;

  v_conflict_hash := null;
  select registry.xml_hash, coalesce(nullif(document.folio, ''), 'BORRADOR')
  into v_conflict_hash, v_conflict_folio
  from public.clc_invoice_registry registry
  left join public.clc_documents document on document.id = registry.clc_id
  join jsonb_array_elements(v_items) item(value)
    on registry.xml_hash = nullif(trim(item.value -> 'cfdi' ->> 'xmlHash'), '')
  where registry.status = 'active'
    and registry.xml_hash is not null
    and not (
      registry.clc_id = v_clc_id
      and coalesce(registry.partida_id, '') = coalesce(item.value ->> 'id', '')
    )
  limit 1;

  if v_conflict_hash is not null then
    raise exception 'Este archivo XML ya está registrado en la CLC %.', v_conflict_folio
      using errcode = '23505';
  end if;

  update public.clc_invoice_registry registry
  set status = 'removed',
      deleted_at = now(),
      deleted_reason = coalesce(registry.deleted_reason, 'Retirada al guardar cambios en la CLC')
  where registry.clc_id = v_clc_id
    and registry.status = 'active'
    and not exists (
      select 1
      from jsonb_array_elements(v_items) item(value)
      where public.clc_normalize_invoice_uuid(item.value ->> 'numFactura') = registry.uuid
        and coalesce(item.value ->> 'id', '') = coalesce(registry.partida_id, '')
    );

  for v_item in select value from jsonb_array_elements(v_items)
  loop
    v_uuid := public.clc_normalize_invoice_uuid(v_item ->> 'numFactura');
    if v_uuid = '' then
      continue;
    end if;

    v_item_id := nullif(trim(v_item ->> 'id'), '');
    v_cfdi := case when jsonb_typeof(v_item -> 'cfdi') = 'object' then v_item -> 'cfdi' else '{}'::jsonb end;

    select id
    into v_registry_id
    from public.clc_invoice_registry
    where uuid = v_uuid and status = 'active'
    for update;

    if v_registry_id is null then
      insert into public.clc_invoice_registry (
        uuid, serie, folio, rfc_emisor, nombre_emisor, rfc_receptor, fecha_factura,
        subtotal, descuento, iva, isr, total, concepto, xml_hash, clc_id, partida_id
      )
      values (
        v_uuid,
        nullif(trim(v_cfdi ->> 'serie'), ''),
        nullif(trim(v_cfdi ->> 'folio'), ''),
        coalesce(nullif(public.clc_normalize_rfc(v_cfdi ->> 'rfcEmisor'), ''), v_provider_rfc),
        coalesce(nullif(trim(v_cfdi ->> 'nombreEmisor'), ''), v_provider_name),
        nullif(public.clc_normalize_rfc(v_cfdi ->> 'rfcReceptor'), ''),
        case when v_item ->> 'fechaFactura' ~ '^\d{4}-\d{2}-\d{2}$' then (v_item ->> 'fechaFactura')::date else null end,
        public.clc_invoice_numeric(v_item, 'subTotal'),
        public.clc_invoice_numeric(v_item, 'descuento'),
        public.clc_invoice_numeric(v_item, 'iva'),
        public.clc_invoice_numeric(v_item, 'isr'),
        public.clc_invoice_numeric(v_item, 'importe'),
        nullif(trim(v_cfdi ->> 'concepto'), ''),
        nullif(trim(v_cfdi ->> 'xmlHash'), ''),
        v_clc_id,
        v_item_id
      );
    else
      update public.clc_invoice_registry
      set serie = nullif(trim(v_cfdi ->> 'serie'), ''),
          folio = nullif(trim(v_cfdi ->> 'folio'), ''),
          rfc_emisor = coalesce(nullif(public.clc_normalize_rfc(v_cfdi ->> 'rfcEmisor'), ''), v_provider_rfc),
          nombre_emisor = coalesce(nullif(trim(v_cfdi ->> 'nombreEmisor'), ''), v_provider_name),
          rfc_receptor = nullif(public.clc_normalize_rfc(v_cfdi ->> 'rfcReceptor'), ''),
          fecha_factura = case when v_item ->> 'fechaFactura' ~ '^\d{4}-\d{2}-\d{2}$' then (v_item ->> 'fechaFactura')::date else null end,
          subtotal = public.clc_invoice_numeric(v_item, 'subTotal'),
          descuento = public.clc_invoice_numeric(v_item, 'descuento'),
          iva = public.clc_invoice_numeric(v_item, 'iva'),
          isr = public.clc_invoice_numeric(v_item, 'isr'),
          total = public.clc_invoice_numeric(v_item, 'importe'),
          concepto = nullif(trim(v_cfdi ->> 'concepto'), ''),
          xml_hash = nullif(trim(v_cfdi ->> 'xmlHash'), ''),
          clc_id = v_clc_id,
          partida_id = v_item_id,
          deleted_at = null,
          deleted_reason = null
      where id = v_registry_id;
    end if;

    v_registry_id := null;
  end loop;
end;
$$;

create or replace function public.clc_save_document(
  p_document jsonb,
  p_app_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
  v_anio integer;
  v_requested_estado text;
  v_draft jsonb;
  v_written_count integer;
begin
  perform public.clc_require_app_key(p_app_key);
  perform public.clc_validate_document_payload(p_document, false);
  perform public.clc_validate_provider_bank_relation(p_document);

  v_id := nullif(trim(p_document ->> 'id'), '');
  v_requested_estado := lower(coalesce(nullif(trim(p_document ->> 'estado'), ''), 'borrador'));
  if v_requested_estado <> 'borrador' or nullif(trim(p_document ->> 'folio'), '') is not null then
    raise exception 'Use clc_finalize_document to finalize CLC documents' using errcode = '22023';
  end if;

  v_anio := public.clc_document_year(p_document);
  v_draft := jsonb_set(p_document, '{estado}', to_jsonb('borrador'::text), true);
  v_draft := jsonb_set(v_draft, '{folio}', to_jsonb(''::text), true);

  insert into public.clc_documents (id, folio, anio, estado, payload)
  values (v_id, null, v_anio, 'borrador', v_draft)
  on conflict (id) do update
  set folio = excluded.folio,
      anio = excluded.anio,
      estado = excluded.estado,
      payload = excluded.payload
  where public.clc_documents.estado <> 'finalizado';

  get diagnostics v_written_count = row_count;
  if v_written_count = 0 then
    raise exception 'Finalized CLC documents cannot be overwritten by clc_save_document' using errcode = '42501';
  end if;

  perform public.clc_sync_invoice_registry(v_draft);
  return jsonb_build_object('document', v_draft) || public.clc_build_app_meta();
end;
$$;

create or replace function public.clc_finalize_document(
  p_document jsonb,
  p_app_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
  v_existing jsonb;
  v_anio integer;
  v_max_existing integer;
  v_next_number integer;
  v_folio text;
  v_now timestamptz;
  v_now_iso text;
  v_finalized jsonb;
  v_written_count integer;
begin
  perform public.clc_require_app_key(p_app_key);
  perform public.clc_validate_document_payload(p_document, true);
  perform public.clc_validate_provider_bank_relation(p_document);

  v_id := nullif(trim(p_document ->> 'id'), '');
  select payload into v_existing from public.clc_documents where id = v_id and estado = 'finalizado';
  if v_existing is not null then
    return jsonb_build_object('finalizedDoc', v_existing) || public.clc_build_app_meta();
  end if;

  v_anio := public.clc_document_year(p_document);
  perform pg_advisory_xact_lock(20260603, v_anio);

  select coalesce(max(nullif(substring(folio from '^CLC-(\d+)/'), '')::integer), 0)
  into v_max_existing
  from public.clc_documents
  where anio = v_anio and estado = 'finalizado';

  insert into public.clc_folio_counters (anio, last_number)
  values (v_anio, v_max_existing)
  on conflict (anio) do update
  set last_number = greatest(public.clc_folio_counters.last_number, excluded.last_number);

  update public.clc_folio_counters
  set last_number = last_number + 1
  where anio = v_anio
  returning last_number into v_next_number;

  v_folio := 'CLC-' || lpad(v_next_number::text, 3, '0') || '/' || v_anio::text;
  v_now := clock_timestamp();
  v_now_iso := to_char(v_now at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_finalized := jsonb_set(p_document, '{folio}', to_jsonb(v_folio), true);
  v_finalized := jsonb_set(v_finalized, '{estado}', to_jsonb('finalizado'::text), true);
  v_finalized := jsonb_set(v_finalized, '{fechaCreacion}', to_jsonb(v_now_iso), true);

  insert into public.clc_documents (id, folio, anio, estado, payload, finalized_at)
  values (v_id, v_folio, v_anio, 'finalizado', v_finalized, v_now)
  on conflict (id) do update
  set folio = excluded.folio,
      anio = excluded.anio,
      estado = excluded.estado,
      payload = excluded.payload,
      finalized_at = coalesce(public.clc_documents.finalized_at, excluded.finalized_at)
  where public.clc_documents.estado <> 'finalizado';

  get diagnostics v_written_count = row_count;
  if v_written_count = 0 then
    raise exception 'Finalized CLC documents cannot be overwritten by clc_finalize_document' using errcode = '42501';
  end if;

  perform public.clc_sync_invoice_registry(v_finalized);
  return jsonb_build_object('finalizedDoc', v_finalized) || public.clc_build_app_meta();
end;
$$;

create or replace function public.clc_delete_document(
  p_id text,
  p_app_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estado text;
  v_deleted_count integer := 0;
begin
  perform public.clc_require_app_key(p_app_key);
  select estado into v_estado from public.clc_documents where id = p_id for update;

  if not found then
    return jsonb_build_object('deletedId', p_id, 'deleted', false) || public.clc_build_app_meta();
  end if;
  if v_estado = 'finalizado' then
    raise exception 'Finalized CLC documents cannot be deleted' using errcode = '42501';
  end if;

  update public.clc_invoice_registry
  set status = 'removed', deleted_at = now(), deleted_reason = 'CLC borrador eliminada'
  where clc_id = p_id and status = 'active';

  delete from public.clc_documents where id = p_id and estado <> 'finalizado';
  get diagnostics v_deleted_count = row_count;
  return jsonb_build_object('deletedId', p_id, 'deleted', v_deleted_count > 0) || public.clc_build_app_meta();
end;
$$;

create or replace function public.clc_retire_invoice(
  p_uuid text,
  p_clc_id text,
  p_partida_id text,
  p_reason text,
  p_app_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_removed_count integer;
  v_next_items jsonb;
begin
  perform public.clc_require_app_key(p_app_key);
  if nullif(trim(p_reason), '') is null then
    raise exception 'El motivo para retirar la factura es obligatorio.' using errcode = '22023';
  end if;

  select estado into v_status from public.clc_documents where id = p_clc_id for update;
  if not found then
    raise exception 'No se encontró la CLC donde está registrada la factura.' using errcode = 'P0002';
  end if;

  -- TODO: permitir una excepción futura únicamente mediante un rol administrativo auditado.
  if v_status = 'finalizado' then
    raise exception 'No se puede retirar una factura de una CLC finalizada.' using errcode = '42501';
  end if;

  update public.clc_invoice_registry
  set status = 'removed',
      deleted_at = now(),
      deleted_reason = trim(p_reason)
  where uuid = public.clc_normalize_invoice_uuid(p_uuid)
    and clc_id = p_clc_id
    and coalesce(partida_id, '') = coalesce(p_partida_id, '')
    and status = 'active';
  get diagnostics v_removed_count = row_count;

  select coalesce(jsonb_agg(item.value order by item.ordinality), '[]'::jsonb)
  into v_next_items
  from jsonb_array_elements(
    case
      when jsonb_typeof((select payload -> 'items' from public.clc_documents where id = p_clc_id)) = 'array'
        then (select payload -> 'items' from public.clc_documents where id = p_clc_id)
      else '[]'::jsonb
    end
  ) with ordinality item(value, ordinality)
  where coalesce(item.value ->> 'id', '') <> coalesce(p_partida_id, '');

  update public.clc_documents
  set payload = jsonb_set(payload, '{items}', v_next_items, true)
  where id = p_clc_id;

  return jsonb_build_object('removed', v_removed_count > 0);
end;
$$;

-- Register existing documents once. If legacy data already contains duplicate
-- UUIDs, the first record becomes active and later saves expose the conflict.
insert into public.clc_invoice_registry (
  uuid, rfc_emisor, nombre_emisor, fecha_factura, subtotal, descuento, iva, isr,
  total, clc_id, partida_id
)
select distinct on (public.clc_normalize_invoice_uuid(item.value ->> 'numFactura'))
  public.clc_normalize_invoice_uuid(item.value ->> 'numFactura'),
  public.clc_normalize_rfc(document.payload ->> 'proveedorRfc'),
  nullif(trim(document.payload ->> 'proveedorNombre'), ''),
  case when item.value ->> 'fechaFactura' ~ '^\d{4}-\d{2}-\d{2}$' then (item.value ->> 'fechaFactura')::date else null end,
  public.clc_invoice_numeric(item.value, 'subTotal'),
  public.clc_invoice_numeric(item.value, 'descuento'),
  public.clc_invoice_numeric(item.value, 'iva'),
  public.clc_invoice_numeric(item.value, 'isr'),
  public.clc_invoice_numeric(item.value, 'importe'),
  document.id,
  nullif(trim(item.value ->> 'id'), '')
from public.clc_documents document
cross join lateral jsonb_array_elements(
  case when jsonb_typeof(document.payload -> 'items') = 'array' then document.payload -> 'items' else '[]'::jsonb end
) item(value)
where public.clc_normalize_invoice_uuid(item.value ->> 'numFactura') <> ''
  and not exists (
    select 1
    from public.clc_invoice_registry registry
    where registry.uuid = public.clc_normalize_invoice_uuid(item.value ->> 'numFactura')
      and registry.status = 'active'
  )
order by public.clc_normalize_invoice_uuid(item.value ->> 'numFactura'), document.updated_at desc
on conflict do nothing;

revoke all on function public.clc_normalize_invoice_uuid(text) from public;
revoke all on function public.clc_normalize_rfc(text) from public;
revoke all on function public.clc_invoice_numeric(jsonb, text) from public;
revoke all on function public.clc_validate_provider_bank_catalogs(jsonb) from public;
revoke all on function public.clc_validate_provider_bank_relation(jsonb) from public;
revoke all on function public.clc_save_catalogs(jsonb, text) from public;
revoke all on function public.clc_check_invoice_uuid(text, text, text, text) from public;
revoke all on function public.clc_sync_invoice_registry(jsonb) from public;
revoke all on function public.clc_retire_invoice(text, text, text, text, text) from public;

grant execute on function public.clc_check_invoice_uuid(text, text, text, text) to anon, authenticated;
grant execute on function public.clc_retire_invoice(text, text, text, text, text) to anon, authenticated;
grant execute on function public.clc_save_catalogs(jsonb, text) to anon, authenticated;

notify pgrst, 'reload schema';
